// Generated by gencpp from file track/Object.msg
// DO NOT EDIT!


#ifndef TRACK_MESSAGE_OBJECT_H
#define TRACK_MESSAGE_OBJECT_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <track/Center.h>
#include <track/Rotate.h>

namespace track
{
template <class ContainerAllocator>
struct Object_
{
  typedef Object_<ContainerAllocator> Type;

  Object_()
    : id(0)
    , center()
    , length(0.0)
    , width(0.0)
    , height(0.0)
    , speedx(0.0)
    , speedy(0.0)
    , slope(0.0)
    , weights(0.0)
    , rotate()  {
    }
  Object_(const ContainerAllocator& _alloc)
    : id(0)
    , center(_alloc)
    , length(0.0)
    , width(0.0)
    , height(0.0)
    , speedx(0.0)
    , speedy(0.0)
    , slope(0.0)
    , weights(0.0)
    , rotate(_alloc)  {
  (void)_alloc;
    }



   typedef int32_t _id_type;
  _id_type id;

   typedef  ::track::Center_<ContainerAllocator>  _center_type;
  _center_type center;

   typedef float _length_type;
  _length_type length;

   typedef float _width_type;
  _width_type width;

   typedef float _height_type;
  _height_type height;

   typedef float _speedx_type;
  _speedx_type speedx;

   typedef float _speedy_type;
  _speedy_type speedy;

   typedef float _slope_type;
  _slope_type slope;

   typedef float _weights_type;
  _weights_type weights;

   typedef  ::track::Rotate_<ContainerAllocator>  _rotate_type;
  _rotate_type rotate;





  typedef boost::shared_ptr< ::track::Object_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::track::Object_<ContainerAllocator> const> ConstPtr;

}; // struct Object_

typedef ::track::Object_<std::allocator<void> > Object;

typedef boost::shared_ptr< ::track::Object > ObjectPtr;
typedef boost::shared_ptr< ::track::Object const> ObjectConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::track::Object_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::track::Object_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace track

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'track': ['/home/sky1/program/rslidar_perception_ws_with_registration_V2.1.5/src/track/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::track::Object_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::track::Object_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::track::Object_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::track::Object_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::track::Object_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::track::Object_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::track::Object_<ContainerAllocator> >
{
  static const char* value()
  {
    return "57f4ef02c648ff1d44cba8fe8606a123";
  }

  static const char* value(const ::track::Object_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x57f4ef02c648ff1dULL;
  static const uint64_t static_value2 = 0x44cba8fe8606a123ULL;
};

template<class ContainerAllocator>
struct DataType< ::track::Object_<ContainerAllocator> >
{
  static const char* value()
  {
    return "track/Object";
  }

  static const char* value(const ::track::Object_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::track::Object_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32  id\n\
Center center\n\
float32 length\n\
float32 width \n\
float32 height\n\
\n\
float32 speedx\n\
float32 speedy\n\
\n\
float32 slope\n\
float32 weights\n\
Rotate  rotate\n\
================================================================================\n\
MSG: track/Center\n\
float32[3] pos\n\
================================================================================\n\
MSG: track/Rotate\n\
float32 x\n\
float32 y\n\
float32 z\n\
float32 w\n\
";
  }

  static const char* value(const ::track::Object_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::track::Object_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.id);
      stream.next(m.center);
      stream.next(m.length);
      stream.next(m.width);
      stream.next(m.height);
      stream.next(m.speedx);
      stream.next(m.speedy);
      stream.next(m.slope);
      stream.next(m.weights);
      stream.next(m.rotate);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Object_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::track::Object_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::track::Object_<ContainerAllocator>& v)
  {
    s << indent << "id: ";
    Printer<int32_t>::stream(s, indent + "  ", v.id);
    s << indent << "center: ";
    s << std::endl;
    Printer< ::track::Center_<ContainerAllocator> >::stream(s, indent + "  ", v.center);
    s << indent << "length: ";
    Printer<float>::stream(s, indent + "  ", v.length);
    s << indent << "width: ";
    Printer<float>::stream(s, indent + "  ", v.width);
    s << indent << "height: ";
    Printer<float>::stream(s, indent + "  ", v.height);
    s << indent << "speedx: ";
    Printer<float>::stream(s, indent + "  ", v.speedx);
    s << indent << "speedy: ";
    Printer<float>::stream(s, indent + "  ", v.speedy);
    s << indent << "slope: ";
    Printer<float>::stream(s, indent + "  ", v.slope);
    s << indent << "weights: ";
    Printer<float>::stream(s, indent + "  ", v.weights);
    s << indent << "rotate: ";
    s << std::endl;
    Printer< ::track::Rotate_<ContainerAllocator> >::stream(s, indent + "  ", v.rotate);
  }
};

} // namespace message_operations
} // namespace ros

#endif // TRACK_MESSAGE_OBJECT_H
