// Generated by gencpp from file cluster/Rotate.msg
// DO NOT EDIT!


#ifndef CLUSTER_MESSAGE_ROTATE_H
#define CLUSTER_MESSAGE_ROTATE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace cluster
{
template <class ContainerAllocator>
struct Rotate_
{
  typedef Rotate_<ContainerAllocator> Type;

  Rotate_()
    : x(0.0)
    , y(0.0)
    , z(0.0)
    , w(0.0)  {
    }
  Rotate_(const ContainerAllocator& _alloc)
    : x(0.0)
    , y(0.0)
    , z(0.0)
    , w(0.0)  {
  (void)_alloc;
    }



   typedef float _x_type;
  _x_type x;

   typedef float _y_type;
  _y_type y;

   typedef float _z_type;
  _z_type z;

   typedef float _w_type;
  _w_type w;





  typedef boost::shared_ptr< ::cluster::Rotate_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::cluster::Rotate_<ContainerAllocator> const> ConstPtr;

}; // struct Rotate_

typedef ::cluster::Rotate_<std::allocator<void> > Rotate;

typedef boost::shared_ptr< ::cluster::Rotate > RotatePtr;
typedef boost::shared_ptr< ::cluster::Rotate const> RotateConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::cluster::Rotate_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::cluster::Rotate_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace cluster

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'cluster': ['/home/sky1/Desktop/rslidar_perception_ws_0106_V1/src/cluster/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::cluster::Rotate_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::cluster::Rotate_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::cluster::Rotate_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::cluster::Rotate_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::cluster::Rotate_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::cluster::Rotate_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::cluster::Rotate_<ContainerAllocator> >
{
  static const char* value()
  {
    return "c3a70de85a9dd451c31fa86cab10a939";
  }

  static const char* value(const ::cluster::Rotate_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xc3a70de85a9dd451ULL;
  static const uint64_t static_value2 = 0xc31fa86cab10a939ULL;
};

template<class ContainerAllocator>
struct DataType< ::cluster::Rotate_<ContainerAllocator> >
{
  static const char* value()
  {
    return "cluster/Rotate";
  }

  static const char* value(const ::cluster::Rotate_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::cluster::Rotate_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32 x\n\
float32 y\n\
float32 z\n\
float32 w\n\
";
  }

  static const char* value(const ::cluster::Rotate_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::cluster::Rotate_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.x);
      stream.next(m.y);
      stream.next(m.z);
      stream.next(m.w);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Rotate_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::cluster::Rotate_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::cluster::Rotate_<ContainerAllocator>& v)
  {
    s << indent << "x: ";
    Printer<float>::stream(s, indent + "  ", v.x);
    s << indent << "y: ";
    Printer<float>::stream(s, indent + "  ", v.y);
    s << indent << "z: ";
    Printer<float>::stream(s, indent + "  ", v.z);
    s << indent << "w: ";
    Printer<float>::stream(s, indent + "  ", v.w);
  }
};

} // namespace message_operations
} // namespace ros

#endif // CLUSTER_MESSAGE_ROTATE_H
