// Generated by gencpp from file segment/Cluster.msg
// DO NOT EDIT!


#ifndef SEGMENT_MESSAGE_CLUSTER_H
#define SEGMENT_MESSAGE_CLUSTER_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <segment/Object.h>

namespace segment
{
template <class ContainerAllocator>
struct Cluster_
{
  typedef Cluster_<ContainerAllocator> Type;

  Cluster_()
    : header()
    , object()  {
    }
  Cluster_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , object(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef std::vector< ::segment::Object_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::segment::Object_<ContainerAllocator> >::other >  _object_type;
  _object_type object;





  typedef boost::shared_ptr< ::segment::Cluster_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::segment::Cluster_<ContainerAllocator> const> ConstPtr;

}; // struct Cluster_

typedef ::segment::Cluster_<std::allocator<void> > Cluster;

typedef boost::shared_ptr< ::segment::Cluster > ClusterPtr;
typedef boost::shared_ptr< ::segment::Cluster const> ClusterConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::segment::Cluster_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::segment::Cluster_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace segment

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': True}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'segment': ['/home/sky1/program/rslidar_perception_ws_with_registration_V1.1/src/segment/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::segment::Cluster_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::segment::Cluster_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::segment::Cluster_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::segment::Cluster_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::segment::Cluster_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::segment::Cluster_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::segment::Cluster_<ContainerAllocator> >
{
  static const char* value()
  {
    return "0df4098de0532e6c85cb8bfaa96c32d9";
  }

  static const char* value(const ::segment::Cluster_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x0df4098de0532e6cULL;
  static const uint64_t static_value2 = 0x85cb8bfaa96c32d9ULL;
};

template<class ContainerAllocator>
struct DataType< ::segment::Cluster_<ContainerAllocator> >
{
  static const char* value()
  {
    return "segment/Cluster";
  }

  static const char* value(const ::segment::Cluster_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::segment::Cluster_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header           header\n\
Object[]           object\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
\n\
================================================================================\n\
MSG: segment/Object\n\
int32  id\n\
Center center\n\
float32 width\n\
float32 height\n\
float32 depth\n\
float32 speedx\n\
float32 speedy\n\
float32 k\n\
Rotate  rotate\n\
================================================================================\n\
MSG: segment/Center\n\
float32[3] pos\n\
================================================================================\n\
MSG: segment/Rotate\n\
float32 x\n\
float32 y\n\
float32 z\n\
float32 w\n\
";
  }

  static const char* value(const ::segment::Cluster_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::segment::Cluster_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.object);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Cluster_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::segment::Cluster_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::segment::Cluster_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "object[]" << std::endl;
    for (size_t i = 0; i < v.object.size(); ++i)
    {
      s << indent << "  object[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::segment::Object_<ContainerAllocator> >::stream(s, indent + "    ", v.object[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // SEGMENT_MESSAGE_CLUSTER_H
