// Generated by gencpp from file segment/ObstSet.msg
// DO NOT EDIT!


#ifndef SEGMENT_MESSAGE_OBSTSET_H
#define SEGMENT_MESSAGE_OBSTSET_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <segment/ObstPointCloud.h>

namespace segment
{
template <class ContainerAllocator>
struct ObstSet_
{
  typedef ObstSet_<ContainerAllocator> Type;

  ObstSet_()
    : obsts()  {
    }
  ObstSet_(const ContainerAllocator& _alloc)
    : obsts(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector< ::segment::ObstPointCloud_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::segment::ObstPointCloud_<ContainerAllocator> >::other >  _obsts_type;
  _obsts_type obsts;





  typedef boost::shared_ptr< ::segment::ObstSet_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::segment::ObstSet_<ContainerAllocator> const> ConstPtr;

}; // struct ObstSet_

typedef ::segment::ObstSet_<std::allocator<void> > ObstSet;

typedef boost::shared_ptr< ::segment::ObstSet > ObstSetPtr;
typedef boost::shared_ptr< ::segment::ObstSet const> ObstSetConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::segment::ObstSet_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::segment::ObstSet_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace segment

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'segment': ['/home/sky1/Desktop/rslidar_perception_ws_0106_V1/src/segment/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::segment::ObstSet_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::segment::ObstSet_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::segment::ObstSet_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::segment::ObstSet_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::segment::ObstSet_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::segment::ObstSet_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::segment::ObstSet_<ContainerAllocator> >
{
  static const char* value()
  {
    return "6dccf9553cd681203dcea38a70f25c51";
  }

  static const char* value(const ::segment::ObstSet_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x6dccf9553cd68120ULL;
  static const uint64_t static_value2 = 0x3dcea38a70f25c51ULL;
};

template<class ContainerAllocator>
struct DataType< ::segment::ObstSet_<ContainerAllocator> >
{
  static const char* value()
  {
    return "segment/ObstSet";
  }

  static const char* value(const ::segment::ObstSet_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::segment::ObstSet_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ObstPointCloud[]  obsts\n\
================================================================================\n\
MSG: segment/ObstPointCloud\n\
Header           header\n\
PointXYZI[]      points\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
\n\
================================================================================\n\
MSG: segment/PointXYZI\n\
float32 x\n\
float32 y\n\
float32 z\n\
float32 intensity\n\
";
  }

  static const char* value(const ::segment::ObstSet_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::segment::ObstSet_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.obsts);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ObstSet_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::segment::ObstSet_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::segment::ObstSet_<ContainerAllocator>& v)
  {
    s << indent << "obsts[]" << std::endl;
    for (size_t i = 0; i < v.obsts.size(); ++i)
    {
      s << indent << "  obsts[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::segment::ObstPointCloud_<ContainerAllocator> >::stream(s, indent + "    ", v.obsts[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // SEGMENT_MESSAGE_OBSTSET_H
